# step 1: build stage
FROM node:14.21.3-alpine AS build-stage

WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .

RUN npm run build

# step 2: production stage
FROM nginx:1.12-alpine
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80

ENTRYPOINT [ "nginx", "-g", "daemon off;" ]
